### Entry point
GET http://localhost:3000/
### findAll()
GET http://localhost:3000/songs
### findOne(':id')
GET http://localhost:3000/songs/1
### create()
POST http://localhost:3000/songs
Content-Type: application/json

{
"title":"Pillow",
"artists": ["Laura Curado"],
"releaseDate":"2022-09-25",
"duration":"03:44"
}
### update('id')
PUT http://localhost:3000/songs/1
### delete(':id')
DELETE http://localhost:3000/songs/1